### ISSUE TITLE
"Add new task list" button crashes app

### ISSUE THREAD

**Issue by JosSamLoh** [done-devs/done#90]
**Describe the bug**
Crashes when clicking "Add new task list" button twice.

**To Reproduce**
1. Click "Add new task list" - Does nothing
2. Click "Add new task list" again - Crashes

**Expected behavior**
The "Add new task list" button creates a new task list.

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 38
 - Version: 0.1.4

**Additional context**
Installed using Flatpak

```
[user@localhost ~]$ flatpak run dev.edfloreshz.Done 
2023-04-25T16:08:42.915569Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::sidebar::model::SidebarComponentModel" id="0x7ffe4a3591a8"}: relm4::component::r#async::builder: new
2023-04-25T16:08:42.915588Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::sidebar::model::SidebarComponentModel" id="0x7ffe4a3591a8"}: relm4::component::r#async::builder: enter
2023-04-25T16:08:42.915596Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::sidebar::model::SidebarComponentModel" id="0x7ffe4a3591a8"}: relm4::component::r#async::builder: exit
2023-04-25T16:08:42.915601Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::sidebar::model::SidebarComponentModel" id="0x7ffe4a3591a8"}: relm4::component::r#async::builder: close time.busy=8.73µs time.idle=26.0µs
2023-04-25T16:08:42.958253Z  INFO update_with_view{input=SelectSmartList(All) component="done::app::App" id="0x7ffe4a3590e0"}: relm4::component::r#async::builder: new
2023-04-25T16:08:42.958269Z  INFO update_with_view{input=SelectSmartList(All) component="done::app::App" id="0x7ffe4a3590e0"}: relm4::component::r#async::builder: enter
2023-04-25T16:08:42.958340Z  INFO update_with_view{input=SelectSmartList(All) component="done::app::App" id="0x7ffe4a3590e0"}: relm4::component::r#async::builder: exit
2023-04-25T16:08:42.958347Z  INFO update_with_view{input=SelectSmartList(All) component="done::app::App" id="0x7ffe4a3590e0"}: relm4::component::r#async::builder: close time.busy=71.1µs time.idle=25.1µs
2023-04-25T16:08:42.958471Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::content::model::ContentModel" id="0x7ffe4a358f50"}: relm4::component::r#async::builder: new
2023-04-25T16:08:42.958477Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::content::model::ContentModel" id="0x7ffe4a358f50"}: relm4::component::r#async::builder: enter
2023-04-25T16:08:42.958498Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::content::model::ContentModel" id="0x7ffe4a358f50"}: relm4::component::r#async::builder: exit
2023-04-25T16:08:42.958503Z  INFO update_with_view{input=SelectSmartList(All) component="done::widgets::content::model::ContentModel" id="0x7ffe4a358f50"}: relm4::component::r#async::builder: close time.busy=20.3µs time.idle=12.5µs
2023-04-25T16:08:42.958600Z  INFO update_with_view{input=SetSmartList(All) component="done::widgets::smart_lists::widget::SmartListContainerModel" id="0x7ffe4a359470"}: relm4::component::r#async::builder: new
2023-04-25T16:08:42.958607Z  INFO update_with_view{input=SetSmartList(All) component="done::widgets::smart_lists::widget::SmartListContainerModel" id="0x7ffe4a359470"}: relm4::component::r#async::builder: enter
2023-04-25T16:08:42.958613Z  INFO update_with_view{input=SetSmartList(All) component="done::widgets::smart_lists::widget::SmartListContainerModel" id="0x7ffe4a359470"}: relm4::component::r#async::builder: exit
2023-04-25T16:08:42.958617Z  INFO update_with_view{input=SetSmartList(All) component="done::widgets::smart_lists::widget::SmartListContainerModel" id="0x7ffe4a359470"}: relm4::component::r#async::builder: close time.busy=6.15µs time.idle=11.1µs
2023-04-25T16:08:45.097619Z  INFO update_with_view{input=AddTaskList("New list") component="done::widgets::lists::model::TaskListsModel" id="0x7ffe4a359150"}: relm4::component::r#async::builder: new
2023-04-25T16:08:45.097646Z  INFO update_with_view{input=AddTaskList("New list") component="done::widgets::lists::model::TaskListsModel" id="0x7ffe4a359150"}: relm4::component::r#async::builder: enter
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/widgets/lists/widget.rs:139:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-04-25T16:08:45.097850Z  INFO update_with_view{input=AddTaskList("New list") component="done::widgets::lists::model::TaskListsModel" id="0x7ffe4a359150"}: relm4::component::r#async::builder: exit
2023-04-25T16:08:45.097864Z  INFO update_with_view{input=AddTaskList("New list") component="done::widgets::lists::model::TaskListsModel" id="0x7ffe4a359150"}: relm4::component::r#async::builder: close time.busy=203µs time.idle=45.7µs
thread 'main' panicked at 'The runtime of the component was shutdown. Maybe you accidentally dropped a controller?: AddTaskList("New list")', /run/build/done/vendor/relm4/src/channel/component.rs:66:34
```

**Comment by edfloreshz** [comment]
Thanks for the report, this will be fixed in the next version. 👍

**Comment by jm9151821** [comment]
Yes, this is happening on linux ubuntu pop OS. Sometimes the List disappear too, but not quite sure on why.

**Comment by edfloreshz** [comment]
Yup, this is happening because a task provider must be selected to create a list, so far Local is the only one that can do that.

**Comment by edfloreshz** [comment]
We have decided to stop developing Done in favor of [Rememberance](https://github.com/dgsasha/remembrance), please consider switching to it.
